api/urls.py
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, CategoryViewSet, UserViewSet
from django.urls import path, include

app_name = 'api'

v1_router = DefaultRouter()

v1_router.register('tasks', TaskViewSet)
v1_router.register('categories', CategoryViewSet)
v1_router.register('users', UserViewSet)

urlpatterns = [
    path('v1/', include(v1_router.urls))
]

tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:slug>/', views.category_tasks, name='category_tasks'),
    path('<slug:category_slug>/<int:pk>/', views.task_detail, name='task_detail')
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("tasks.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

api/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'Категория {self.title}'


class Task(models.Model):
    LOW = 'LW'
    MIDDLE = 'MD'
    HIGH = 'HG'

    PRIORITY_CHOICES = [
        (LOW, 'Низкий'),
        (MIDDLE, 'Средний'),
        (HIGH, 'Высокий')
    ]

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='tasks')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=255)
    deadline = models.DateTimeField(null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    done = models.BooleanField(default=False)
    priority = models.CharField(max_length=2, choices=PRIORITY_CHOICES, default=LOW)
    attachment = models.FileField(upload_to='uploads/', verbose_name='Вложение', null=True, blank=True)

    class Meta:
        ordering = ['-deadline', 'done']
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f'Задача {self.title}'

api/views.py
from rest_framework import viewsets
from tasks.models import Task, Category, User
from .serializers import TaskSerializer, CategorySerializer, UserSerializer


class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

tasks/views.py
from django.shortcuts import render, get_object_or_404
from .models import Task, Category


def index(request):
    tasks = Task.objects.filter(done=False)
    context = {'tasks': tasks}
    return render(request, 'task_list.html', context)


def category_tasks(request, slug):
    category = get_object_or_404(Category, slug=slug)
    context = {'tasks': category.tasks.all()}
    return render(request, 'task_list.html', context)


def task_detail(request, category_slug, pk):
    category = get_object_or_404(Category, slug=category_slug)
    task = get_object_or_404(Task, pk=pk)
    context = {'task': task}
    return render(request, 'task_detail.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css" rel="stylesheet"/>
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet"/>
    <title>Планировщик</title>
  </head>
  <body>
    {% block content %}{% endblock %}
    {% include 'includes/footer.html' %}
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js"></script>
  </body>
</html>

templates/includes/footer.html
{% load static %}
<footer class="gradient-custom-2 text-center py-5">
  <p style="color: white;"><img src="{% static 'img/logo.jpg' %}" alt="Check" width="20"> TASK APP 2022</p>
</footer>

templates/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main class="vh-100 gradient-custom-2">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-12 col-xl-10">
            <div class="card mask-custom">
              <div class="card-body p-4 text-white">
                <div class="text-center pt-3 pb-2">
                    {% if task.done %}
                        <i class="fas fa-check fa-8x text-success me-3"></i>
                    {% else %}
                        <i class="fas fa-xmark fa-8x text-danger me-3"></i>
                      {% endif %}
                  <h2 class="my-4">{{ task.title }}</h2>
                  <h4>Family</h4>
                </div>
                <div class="row">
                    <div class="col-6 text-center pb-2"><i class="fas fa-hourglass-half me-2 text-warning"></i>{{ task.deadline|default_if_none:'Без срока' }}</div>
                    <div class="col-6 text-center pb-2"><h6 class="mb-0"><span class="badge">{{ task.get_priority_display }}</span></h6></div>
                </div>
                <div class="row">
                    <div class="col-12 text-center fs-4">{{ task.description|safe }}</div>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

templates/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="vh-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="card mask-custom">
          <div class="card-body p-4 text-white">
            <div class="text-center pt-3 pb-2">
              <img src="{% static 'img/check1.webp' %}" alt="Check" width="60">
              <h2 class="my-4">Список задач</h2>
            </div>
            <table class="table text-white mb-0">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">Задача</th>
                  <th scope="col">Категория</th>
                  <th scope="col">Приоритет</th>
                  <th scope="col">Дедлайн</th>
                  <th scope="col">Статус</th>
                </tr>
              </thead>
              <tbody>
              {% for task in tasks %}
                <tr class="fw-normal">
                  <th>{{ forloop.counter }}</th>
                  <td class="align-middle">
                    <a href="{% url 'task_detail' task.category.slug task.pk %}" title="">{{ task.title}}</a>
                  </td>
                  <td class="align-middle">
                    <a href="{% url 'category_tasks' task.category.slug %}" title="">{{ task.category.title }}</a>
                  </td>
                  <td class="align-middle">
                    <h6 class="mb-0"><span class="badge">{{ task.get_priority_display }}</span></h6>
                  </td>
                  <td class="align-middle">
                    <i class="fas fa-hourglass-half me-2 text-warning"></i>{{ task.deadline|default_if_none:'Без срока' }}
                  </td>
                  <td class="align-middle">
                      {% if task.done %}
                        <i class="fas fa-check fa-lg text-success me-3"></i>
                      {% else %}
                        <i class="fas fa-xmark fa-lg text-danger me-3"></i>
                      {% endif %}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}